name: Shared TruffleHog Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  Secret-Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Step 1: Scan Pull Requests (Diff between base branch and incoming PR branch)
      - name: TruffleHog PR Scan
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified

      # Step 2: Scan Direct Pushes (Diff between the commits pushed)
      - name: TruffleHog Push Scan
        if: github.event_name == 'push'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.event.after }}
          extra_args: --only-verified